package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class CaseBuyer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.user_general_id
     *
     * @mbg.generated
     */
    private String userGeneralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.fetch_confirm
     *
     * @mbg.generated
     */
    private Short fetchConfirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.gender
     *
     * @mbg.generated
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.famname
     *
     * @mbg.generated
     */
    private String famname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.famname_kana
     *
     * @mbg.generated
     */
    private String famnameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.givename
     *
     * @mbg.generated
     */
    private String givename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.givename_kana
     *
     * @mbg.generated
     */
    private String givenameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.fullname
     *
     * @mbg.generated
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.fullname_kana
     *
     * @mbg.generated
     */
    private String fullnameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.addr1
     *
     * @mbg.generated
     */
    private String addr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.addr2
     *
     * @mbg.generated
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.addr3
     *
     * @mbg.generated
     */
    private String addr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.user_general_cert
     *
     * @mbg.generated
     */
    private byte[] userGeneralCert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_buyer.user_general_cert_back
     *
     * @mbg.generated
     */
    private byte[] userGeneralCertBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.id
     *
     * @return the value of case_buyer.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.id
     *
     * @param id the value for case_buyer.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.case_id
     *
     * @return the value of case_buyer.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.case_id
     *
     * @param caseId the value for case_buyer.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.user_general_id
     *
     * @return the value of case_buyer.user_general_id
     *
     * @mbg.generated
     */
    public String getUserGeneralId() {
        return userGeneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.user_general_id
     *
     * @param userGeneralId the value for case_buyer.user_general_id
     *
     * @mbg.generated
     */
    public void setUserGeneralId(String userGeneralId) {
        this.userGeneralId = userGeneralId == null ? null : userGeneralId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.fetch_confirm
     *
     * @return the value of case_buyer.fetch_confirm
     *
     * @mbg.generated
     */
    public Short getFetchConfirm() {
        return fetchConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.fetch_confirm
     *
     * @param fetchConfirm the value for case_buyer.fetch_confirm
     *
     * @mbg.generated
     */
    public void setFetchConfirm(Short fetchConfirm) {
        this.fetchConfirm = fetchConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.gender
     *
     * @return the value of case_buyer.gender
     *
     * @mbg.generated
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.gender
     *
     * @param gender the value for case_buyer.gender
     *
     * @mbg.generated
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.famname
     *
     * @return the value of case_buyer.famname
     *
     * @mbg.generated
     */
    public String getFamname() {
        return famname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.famname
     *
     * @param famname the value for case_buyer.famname
     *
     * @mbg.generated
     */
    public void setFamname(String famname) {
        this.famname = famname == null ? null : famname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.famname_kana
     *
     * @return the value of case_buyer.famname_kana
     *
     * @mbg.generated
     */
    public String getFamnameKana() {
        return famnameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.famname_kana
     *
     * @param famnameKana the value for case_buyer.famname_kana
     *
     * @mbg.generated
     */
    public void setFamnameKana(String famnameKana) {
        this.famnameKana = famnameKana == null ? null : famnameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.givename
     *
     * @return the value of case_buyer.givename
     *
     * @mbg.generated
     */
    public String getGivename() {
        return givename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.givename
     *
     * @param givename the value for case_buyer.givename
     *
     * @mbg.generated
     */
    public void setGivename(String givename) {
        this.givename = givename == null ? null : givename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.givename_kana
     *
     * @return the value of case_buyer.givename_kana
     *
     * @mbg.generated
     */
    public String getGivenameKana() {
        return givenameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.givename_kana
     *
     * @param givenameKana the value for case_buyer.givename_kana
     *
     * @mbg.generated
     */
    public void setGivenameKana(String givenameKana) {
        this.givenameKana = givenameKana == null ? null : givenameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.fullname
     *
     * @return the value of case_buyer.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.fullname
     *
     * @param fullname the value for case_buyer.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.fullname_kana
     *
     * @return the value of case_buyer.fullname_kana
     *
     * @mbg.generated
     */
    public String getFullnameKana() {
        return fullnameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.fullname_kana
     *
     * @param fullnameKana the value for case_buyer.fullname_kana
     *
     * @mbg.generated
     */
    public void setFullnameKana(String fullnameKana) {
        this.fullnameKana = fullnameKana == null ? null : fullnameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.birthday
     *
     * @return the value of case_buyer.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.birthday
     *
     * @param birthday the value for case_buyer.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.postcode
     *
     * @return the value of case_buyer.postcode
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.postcode
     *
     * @param postcode the value for case_buyer.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.addr1
     *
     * @return the value of case_buyer.addr1
     *
     * @mbg.generated
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.addr1
     *
     * @param addr1 the value for case_buyer.addr1
     *
     * @mbg.generated
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.addr2
     *
     * @return the value of case_buyer.addr2
     *
     * @mbg.generated
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.addr2
     *
     * @param addr2 the value for case_buyer.addr2
     *
     * @mbg.generated
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.addr3
     *
     * @return the value of case_buyer.addr3
     *
     * @mbg.generated
     */
    public String getAddr3() {
        return addr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.addr3
     *
     * @param addr3 the value for case_buyer.addr3
     *
     * @mbg.generated
     */
    public void setAddr3(String addr3) {
        this.addr3 = addr3 == null ? null : addr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.status
     *
     * @return the value of case_buyer.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.status
     *
     * @param status the value for case_buyer.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.remark
     *
     * @return the value of case_buyer.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.remark
     *
     * @param remark the value for case_buyer.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.created_by
     *
     * @return the value of case_buyer.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.created_by
     *
     * @param createdBy the value for case_buyer.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.create_time
     *
     * @return the value of case_buyer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.create_time
     *
     * @param createTime the value for case_buyer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.updated_by
     *
     * @return the value of case_buyer.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.updated_by
     *
     * @param updatedBy the value for case_buyer.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.update_time
     *
     * @return the value of case_buyer.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.update_time
     *
     * @param updateTime the value for case_buyer.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.user_general_cert
     *
     * @return the value of case_buyer.user_general_cert
     *
     * @mbg.generated
     */
    public byte[] getUserGeneralCert() {
        return userGeneralCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.user_general_cert
     *
     * @param userGeneralCert the value for case_buyer.user_general_cert
     *
     * @mbg.generated
     */
    public void setUserGeneralCert(byte[] userGeneralCert) {
        this.userGeneralCert = userGeneralCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_buyer.user_general_cert_back
     *
     * @return the value of case_buyer.user_general_cert_back
     *
     * @mbg.generated
     */
    public byte[] getUserGeneralCertBack() {
        return userGeneralCertBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_buyer.user_general_cert_back
     *
     * @param userGeneralCertBack the value for case_buyer.user_general_cert_back
     *
     * @mbg.generated
     */
    public void setUserGeneralCertBack(byte[] userGeneralCertBack) {
        this.userGeneralCertBack = userGeneralCertBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", caseId=").append(caseId);
        sb.append(", userGeneralId=").append(userGeneralId);
        sb.append(", fetchConfirm=").append(fetchConfirm);
        sb.append(", gender=").append(gender);
        sb.append(", famname=").append(famname);
        sb.append(", famnameKana=").append(famnameKana);
        sb.append(", givename=").append(givename);
        sb.append(", givenameKana=").append(givenameKana);
        sb.append(", fullname=").append(fullname);
        sb.append(", fullnameKana=").append(fullnameKana);
        sb.append(", birthday=").append(birthday);
        sb.append(", postcode=").append(postcode);
        sb.append(", addr1=").append(addr1);
        sb.append(", addr2=").append(addr2);
        sb.append(", addr3=").append(addr3);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userGeneralCert=").append(userGeneralCert);
        sb.append(", userGeneralCertBack=").append(userGeneralCertBack);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}