package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class CaseSeller implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.user_general_id
     *
     * @mbg.generated
     */
    private String userGeneralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.verify
     *
     * @mbg.generated
     */
    private Short verify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_seller.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_seller
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.id
     *
     * @return the value of case_seller.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.id
     *
     * @param id the value for case_seller.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.case_id
     *
     * @return the value of case_seller.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.case_id
     *
     * @param caseId the value for case_seller.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.user_general_id
     *
     * @return the value of case_seller.user_general_id
     *
     * @mbg.generated
     */
    public String getUserGeneralId() {
        return userGeneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.user_general_id
     *
     * @param userGeneralId the value for case_seller.user_general_id
     *
     * @mbg.generated
     */
    public void setUserGeneralId(String userGeneralId) {
        this.userGeneralId = userGeneralId == null ? null : userGeneralId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.status
     *
     * @return the value of case_seller.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.status
     *
     * @param status the value for case_seller.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.verify
     *
     * @return the value of case_seller.verify
     *
     * @mbg.generated
     */
    public Short getVerify() {
        return verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.verify
     *
     * @param verify the value for case_seller.verify
     *
     * @mbg.generated
     */
    public void setVerify(Short verify) {
        this.verify = verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.remark
     *
     * @return the value of case_seller.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.remark
     *
     * @param remark the value for case_seller.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.created_by
     *
     * @return the value of case_seller.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.created_by
     *
     * @param createdBy the value for case_seller.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.create_time
     *
     * @return the value of case_seller.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.create_time
     *
     * @param createTime the value for case_seller.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.updated_by
     *
     * @return the value of case_seller.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.updated_by
     *
     * @param updatedBy the value for case_seller.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_seller.update_time
     *
     * @return the value of case_seller.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_seller.update_time
     *
     * @param updateTime the value for case_seller.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_seller
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", caseId=").append(caseId);
        sb.append(", userGeneralId=").append(userGeneralId);
        sb.append(", status=").append(status);
        sb.append(", verify=").append(verify);
        sb.append(", remark=").append(remark);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}