package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class CaseEstateRecordUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.estate_record_id
     *
     * @mbg.generated
     */
    private String estateRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.user_general_id
     *
     * @mbg.generated
     */
    private String userGeneralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.id
     *
     * @return the value of case_estate_record_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.id
     *
     * @param id the value for case_estate_record_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.estate_record_id
     *
     * @return the value of case_estate_record_user.estate_record_id
     *
     * @mbg.generated
     */
    public String getEstateRecordId() {
        return estateRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.estate_record_id
     *
     * @param estateRecordId the value for case_estate_record_user.estate_record_id
     *
     * @mbg.generated
     */
    public void setEstateRecordId(String estateRecordId) {
        this.estateRecordId = estateRecordId == null ? null : estateRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.user_general_id
     *
     * @return the value of case_estate_record_user.user_general_id
     *
     * @mbg.generated
     */
    public String getUserGeneralId() {
        return userGeneralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.user_general_id
     *
     * @param userGeneralId the value for case_estate_record_user.user_general_id
     *
     * @mbg.generated
     */
    public void setUserGeneralId(String userGeneralId) {
        this.userGeneralId = userGeneralId == null ? null : userGeneralId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.status
     *
     * @return the value of case_estate_record_user.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.status
     *
     * @param status the value for case_estate_record_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.remark
     *
     * @return the value of case_estate_record_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.remark
     *
     * @param remark the value for case_estate_record_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.create_time
     *
     * @return the value of case_estate_record_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.create_time
     *
     * @param createTime the value for case_estate_record_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record_user.update_time
     *
     * @return the value of case_estate_record_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record_user.update_time
     *
     * @param updateTime the value for case_estate_record_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", estateRecordId=").append(estateRecordId);
        sb.append(", userGeneralId=").append(userGeneralId);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}