package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class CaseEstateRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.record_id
     *
     * @mbg.generated
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.case_id
     *
     * @mbg.generated
     */
    private String caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.record_type
     *
     * @mbg.generated
     */
    private Short recordType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.estate_id
     *
     * @mbg.generated
     */
    private String estateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.addr1
     *
     * @mbg.generated
     */
    private String addr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.addr_code
     *
     * @mbg.generated
     */
    private String addrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.addr2
     *
     * @mbg.generated
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.house_id
     *
     * @mbg.generated
     */
    private String houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.estate_no
     *
     * @mbg.generated
     */
    private String estateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.struct
     *
     * @mbg.generated
     */
    private String struct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.fetch_status
     *
     * @mbg.generated
     */
    private Short fetchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.fetch_msg
     *
     * @mbg.generated
     */
    private String fetchMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.record
     *
     * @mbg.generated
     */
    private String record;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column case_estate_record.cert_image
     *
     * @mbg.generated
     */
    private byte[] certImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table case_estate_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.record_id
     *
     * @return the value of case_estate_record.record_id
     *
     * @mbg.generated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.record_id
     *
     * @param recordId the value for case_estate_record.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.case_id
     *
     * @return the value of case_estate_record.case_id
     *
     * @mbg.generated
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.case_id
     *
     * @param caseId the value for case_estate_record.case_id
     *
     * @mbg.generated
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.record_type
     *
     * @return the value of case_estate_record.record_type
     *
     * @mbg.generated
     */
    public Short getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.record_type
     *
     * @param recordType the value for case_estate_record.record_type
     *
     * @mbg.generated
     */
    public void setRecordType(Short recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.estate_id
     *
     * @return the value of case_estate_record.estate_id
     *
     * @mbg.generated
     */
    public String getEstateId() {
        return estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.estate_id
     *
     * @param estateId the value for case_estate_record.estate_id
     *
     * @mbg.generated
     */
    public void setEstateId(String estateId) {
        this.estateId = estateId == null ? null : estateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.addr1
     *
     * @return the value of case_estate_record.addr1
     *
     * @mbg.generated
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.addr1
     *
     * @param addr1 the value for case_estate_record.addr1
     *
     * @mbg.generated
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.addr
     *
     * @return the value of case_estate_record.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.addr
     *
     * @param addr the value for case_estate_record.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.addr_code
     *
     * @return the value of case_estate_record.addr_code
     *
     * @mbg.generated
     */
    public String getAddrCode() {
        return addrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.addr_code
     *
     * @param addrCode the value for case_estate_record.addr_code
     *
     * @mbg.generated
     */
    public void setAddrCode(String addrCode) {
        this.addrCode = addrCode == null ? null : addrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.addr2
     *
     * @return the value of case_estate_record.addr2
     *
     * @mbg.generated
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.addr2
     *
     * @param addr2 the value for case_estate_record.addr2
     *
     * @mbg.generated
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.house_id
     *
     * @return the value of case_estate_record.house_id
     *
     * @mbg.generated
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.house_id
     *
     * @param houseId the value for case_estate_record.house_id
     *
     * @mbg.generated
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.type
     *
     * @return the value of case_estate_record.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.type
     *
     * @param type the value for case_estate_record.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.estate_no
     *
     * @return the value of case_estate_record.estate_no
     *
     * @mbg.generated
     */
    public String getEstateNo() {
        return estateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.estate_no
     *
     * @param estateNo the value for case_estate_record.estate_no
     *
     * @mbg.generated
     */
    public void setEstateNo(String estateNo) {
        this.estateNo = estateNo == null ? null : estateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.category
     *
     * @return the value of case_estate_record.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.category
     *
     * @param category the value for case_estate_record.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.struct
     *
     * @return the value of case_estate_record.struct
     *
     * @mbg.generated
     */
    public String getStruct() {
        return struct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.struct
     *
     * @param struct the value for case_estate_record.struct
     *
     * @mbg.generated
     */
    public void setStruct(String struct) {
        this.struct = struct == null ? null : struct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.area
     *
     * @return the value of case_estate_record.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.area
     *
     * @param area the value for case_estate_record.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.status
     *
     * @return the value of case_estate_record.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.status
     *
     * @param status the value for case_estate_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.remark
     *
     * @return the value of case_estate_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.remark
     *
     * @param remark the value for case_estate_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.fetch_status
     *
     * @return the value of case_estate_record.fetch_status
     *
     * @mbg.generated
     */
    public Short getFetchStatus() {
        return fetchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.fetch_status
     *
     * @param fetchStatus the value for case_estate_record.fetch_status
     *
     * @mbg.generated
     */
    public void setFetchStatus(Short fetchStatus) {
        this.fetchStatus = fetchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.fetch_msg
     *
     * @return the value of case_estate_record.fetch_msg
     *
     * @mbg.generated
     */
    public String getFetchMsg() {
        return fetchMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.fetch_msg
     *
     * @param fetchMsg the value for case_estate_record.fetch_msg
     *
     * @mbg.generated
     */
    public void setFetchMsg(String fetchMsg) {
        this.fetchMsg = fetchMsg == null ? null : fetchMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.created_by
     *
     * @return the value of case_estate_record.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.created_by
     *
     * @param createdBy the value for case_estate_record.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.create_time
     *
     * @return the value of case_estate_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.create_time
     *
     * @param createTime the value for case_estate_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.updated_by
     *
     * @return the value of case_estate_record.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.updated_by
     *
     * @param updatedBy the value for case_estate_record.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.update_time
     *
     * @return the value of case_estate_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.update_time
     *
     * @param updateTime the value for case_estate_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.record
     *
     * @return the value of case_estate_record.record
     *
     * @mbg.generated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.record
     *
     * @param record the value for case_estate_record.record
     *
     * @mbg.generated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column case_estate_record.cert_image
     *
     * @return the value of case_estate_record.cert_image
     *
     * @mbg.generated
     */
    public byte[] getCertImage() {
        return certImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column case_estate_record.cert_image
     *
     * @param certImage the value for case_estate_record.cert_image
     *
     * @mbg.generated
     */
    public void setCertImage(byte[] certImage) {
        this.certImage = certImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recordId=").append(recordId);
        sb.append(", caseId=").append(caseId);
        sb.append(", recordType=").append(recordType);
        sb.append(", estateId=").append(estateId);
        sb.append(", addr1=").append(addr1);
        sb.append(", addr=").append(addr);
        sb.append(", addrCode=").append(addrCode);
        sb.append(", addr2=").append(addr2);
        sb.append(", houseId=").append(houseId);
        sb.append(", type=").append(type);
        sb.append(", estateNo=").append(estateNo);
        sb.append(", category=").append(category);
        sb.append(", struct=").append(struct);
        sb.append(", area=").append(area);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", fetchStatus=").append(fetchStatus);
        sb.append(", fetchMsg=").append(fetchMsg);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", record=").append(record);
        sb.append(", certImage=").append(certImage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}