package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class EstateProtectionOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.set_id
     *
     * @mbg.generated
     */
    private String setId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.actual_price
     *
     * @mbg.generated
     */
    private Long actualPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.offset_amount
     *
     * @mbg.generated
     */
    private Long offsetAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.pay_tag
     *
     * @mbg.generated
     */
    private Short payTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.pay_amount
     *
     * @mbg.generated
     */
    private Long payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.pay_times
     *
     * @mbg.generated
     */
    private Integer payTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_protection_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.order_id
     *
     * @return the value of estate_protection_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.order_id
     *
     * @param orderId the value for estate_protection_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.order_no
     *
     * @return the value of estate_protection_order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.order_no
     *
     * @param orderNo the value for estate_protection_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.set_id
     *
     * @return the value of estate_protection_order.set_id
     *
     * @mbg.generated
     */
    public String getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.set_id
     *
     * @param setId the value for estate_protection_order.set_id
     *
     * @mbg.generated
     */
    public void setSetId(String setId) {
        this.setId = setId == null ? null : setId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.customer_id
     *
     * @return the value of estate_protection_order.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.customer_id
     *
     * @param customerId the value for estate_protection_order.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.start_date
     *
     * @return the value of estate_protection_order.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.start_date
     *
     * @param startDate the value for estate_protection_order.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.end_date
     *
     * @return the value of estate_protection_order.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.end_date
     *
     * @param endDate the value for estate_protection_order.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.name
     *
     * @return the value of estate_protection_order.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.name
     *
     * @param name the value for estate_protection_order.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.price
     *
     * @return the value of estate_protection_order.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.price
     *
     * @param price the value for estate_protection_order.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.actual_price
     *
     * @return the value of estate_protection_order.actual_price
     *
     * @mbg.generated
     */
    public Long getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.actual_price
     *
     * @param actualPrice the value for estate_protection_order.actual_price
     *
     * @mbg.generated
     */
    public void setActualPrice(Long actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.offset_amount
     *
     * @return the value of estate_protection_order.offset_amount
     *
     * @mbg.generated
     */
    public Long getOffsetAmount() {
        return offsetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.offset_amount
     *
     * @param offsetAmount the value for estate_protection_order.offset_amount
     *
     * @mbg.generated
     */
    public void setOffsetAmount(Long offsetAmount) {
        this.offsetAmount = offsetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.pay_tag
     *
     * @return the value of estate_protection_order.pay_tag
     *
     * @mbg.generated
     */
    public Short getPayTag() {
        return payTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.pay_tag
     *
     * @param payTag the value for estate_protection_order.pay_tag
     *
     * @mbg.generated
     */
    public void setPayTag(Short payTag) {
        this.payTag = payTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.pay_time
     *
     * @return the value of estate_protection_order.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.pay_time
     *
     * @param payTime the value for estate_protection_order.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.pay_amount
     *
     * @return the value of estate_protection_order.pay_amount
     *
     * @mbg.generated
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.pay_amount
     *
     * @param payAmount the value for estate_protection_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.pay_times
     *
     * @return the value of estate_protection_order.pay_times
     *
     * @mbg.generated
     */
    public Integer getPayTimes() {
        return payTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.pay_times
     *
     * @param payTimes the value for estate_protection_order.pay_times
     *
     * @mbg.generated
     */
    public void setPayTimes(Integer payTimes) {
        this.payTimes = payTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.status
     *
     * @return the value of estate_protection_order.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.status
     *
     * @param status the value for estate_protection_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.created_by
     *
     * @return the value of estate_protection_order.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.created_by
     *
     * @param createdBy the value for estate_protection_order.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.create_time
     *
     * @return the value of estate_protection_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.create_time
     *
     * @param createTime the value for estate_protection_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.updated_by
     *
     * @return the value of estate_protection_order.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.updated_by
     *
     * @param updatedBy the value for estate_protection_order.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.update_time
     *
     * @return the value of estate_protection_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.update_time
     *
     * @param updateTime the value for estate_protection_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_protection_order.remark
     *
     * @return the value of estate_protection_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_protection_order.remark
     *
     * @param remark the value for estate_protection_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", setId=").append(setId);
        sb.append(", customerId=").append(customerId);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", actualPrice=").append(actualPrice);
        sb.append(", offsetAmount=").append(offsetAmount);
        sb.append(", payTag=").append(payTag);
        sb.append(", payTime=").append(payTime);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", payTimes=").append(payTimes);
        sb.append(", status=").append(status);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}