package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class EstateInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.estate_id
     *
     * @mbg.generated
     */
    private String estateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.set_id
     *
     * @mbg.generated
     */
    private String setId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.addr_code
     *
     * @mbg.generated
     */
    private String addrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.addr2
     *
     * @mbg.generated
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.house_id
     *
     * @mbg.generated
     */
    private String houseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.estate_no
     *
     * @mbg.generated
     */
    private String estateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.struct
     *
     * @mbg.generated
     */
    private String struct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.pdf_path
     *
     * @mbg.generated
     */
    private String pdfPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.record
     *
     * @mbg.generated
     */
    private String record;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estate_info.cert_image
     *
     * @mbg.generated
     */
    private byte[] certImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table estate_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.estate_id
     *
     * @return the value of estate_info.estate_id
     *
     * @mbg.generated
     */
    public String getEstateId() {
        return estateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.estate_id
     *
     * @param estateId the value for estate_info.estate_id
     *
     * @mbg.generated
     */
    public void setEstateId(String estateId) {
        this.estateId = estateId == null ? null : estateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.set_id
     *
     * @return the value of estate_info.set_id
     *
     * @mbg.generated
     */
    public String getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.set_id
     *
     * @param setId the value for estate_info.set_id
     *
     * @mbg.generated
     */
    public void setSetId(String setId) {
        this.setId = setId == null ? null : setId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.addr
     *
     * @return the value of estate_info.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.addr
     *
     * @param addr the value for estate_info.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.addr_code
     *
     * @return the value of estate_info.addr_code
     *
     * @mbg.generated
     */
    public String getAddrCode() {
        return addrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.addr_code
     *
     * @param addrCode the value for estate_info.addr_code
     *
     * @mbg.generated
     */
    public void setAddrCode(String addrCode) {
        this.addrCode = addrCode == null ? null : addrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.addr2
     *
     * @return the value of estate_info.addr2
     *
     * @mbg.generated
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.addr2
     *
     * @param addr2 the value for estate_info.addr2
     *
     * @mbg.generated
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.house_id
     *
     * @return the value of estate_info.house_id
     *
     * @mbg.generated
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.house_id
     *
     * @param houseId the value for estate_info.house_id
     *
     * @mbg.generated
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.type
     *
     * @return the value of estate_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.type
     *
     * @param type the value for estate_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.estate_no
     *
     * @return the value of estate_info.estate_no
     *
     * @mbg.generated
     */
    public String getEstateNo() {
        return estateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.estate_no
     *
     * @param estateNo the value for estate_info.estate_no
     *
     * @mbg.generated
     */
    public void setEstateNo(String estateNo) {
        this.estateNo = estateNo == null ? null : estateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.category
     *
     * @return the value of estate_info.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.category
     *
     * @param category the value for estate_info.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.struct
     *
     * @return the value of estate_info.struct
     *
     * @mbg.generated
     */
    public String getStruct() {
        return struct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.struct
     *
     * @param struct the value for estate_info.struct
     *
     * @mbg.generated
     */
    public void setStruct(String struct) {
        this.struct = struct == null ? null : struct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.area
     *
     * @return the value of estate_info.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.area
     *
     * @param area the value for estate_info.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.pdf_path
     *
     * @return the value of estate_info.pdf_path
     *
     * @mbg.generated
     */
    public String getPdfPath() {
        return pdfPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.pdf_path
     *
     * @param pdfPath the value for estate_info.pdf_path
     *
     * @mbg.generated
     */
    public void setPdfPath(String pdfPath) {
        this.pdfPath = pdfPath == null ? null : pdfPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.status
     *
     * @return the value of estate_info.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.status
     *
     * @param status the value for estate_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.remark
     *
     * @return the value of estate_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.remark
     *
     * @param remark the value for estate_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.created_by
     *
     * @return the value of estate_info.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.created_by
     *
     * @param createdBy the value for estate_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.create_time
     *
     * @return the value of estate_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.create_time
     *
     * @param createTime the value for estate_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.updated_by
     *
     * @return the value of estate_info.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.updated_by
     *
     * @param updatedBy the value for estate_info.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.update_time
     *
     * @return the value of estate_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.update_time
     *
     * @param updateTime the value for estate_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.record
     *
     * @return the value of estate_info.record
     *
     * @mbg.generated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.record
     *
     * @param record the value for estate_info.record
     *
     * @mbg.generated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estate_info.cert_image
     *
     * @return the value of estate_info.cert_image
     *
     * @mbg.generated
     */
    public byte[] getCertImage() {
        return certImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estate_info.cert_image
     *
     * @param certImage the value for estate_info.cert_image
     *
     * @mbg.generated
     */
    public void setCertImage(byte[] certImage) {
        this.certImage = certImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", estateId=").append(estateId);
        sb.append(", setId=").append(setId);
        sb.append(", addr=").append(addr);
        sb.append(", addrCode=").append(addrCode);
        sb.append(", addr2=").append(addr2);
        sb.append(", houseId=").append(houseId);
        sb.append(", type=").append(type);
        sb.append(", estateNo=").append(estateNo);
        sb.append(", category=").append(category);
        sb.append(", struct=").append(struct);
        sb.append(", area=").append(area);
        sb.append(", pdfPath=").append(pdfPath);
        sb.append(", status=").append(status);
        sb.append(", remark=").append(remark);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", record=").append(record);
        sb.append(", certImage=").append(certImage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}