package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class LawApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.corp_name
     *
     * @mbg.generated
     */
    private String corpName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.corp_rpt_name
     *
     * @mbg.generated
     */
    private String corpRptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.corp_rpt_name_kana
     *
     * @mbg.generated
     */
    private String corpRptNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.corp_addr
     *
     * @mbg.generated
     */
    private String corpAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.corp_phone
     *
     * @mbg.generated
     */
    private String corpPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.applicant_name
     *
     * @mbg.generated
     */
    private String applicantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.applicant_name_kana
     *
     * @mbg.generated
     */
    private String applicantNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.applicant_dept
     *
     * @mbg.generated
     */
    private String applicantDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.applicant_phone
     *
     * @mbg.generated
     */
    private String applicantPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.applicant_email
     *
     * @mbg.generated
     */
    private String applicantEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.reject_reason
     *
     * @mbg.generated
     */
    private String rejectReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.reject_time
     *
     * @mbg.generated
     */
    private Date rejectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_apply.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.id
     *
     * @return the value of law_apply.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.id
     *
     * @param id the value for law_apply.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.corp_name
     *
     * @return the value of law_apply.corp_name
     *
     * @mbg.generated
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.corp_name
     *
     * @param corpName the value for law_apply.corp_name
     *
     * @mbg.generated
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName == null ? null : corpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.corp_rpt_name
     *
     * @return the value of law_apply.corp_rpt_name
     *
     * @mbg.generated
     */
    public String getCorpRptName() {
        return corpRptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.corp_rpt_name
     *
     * @param corpRptName the value for law_apply.corp_rpt_name
     *
     * @mbg.generated
     */
    public void setCorpRptName(String corpRptName) {
        this.corpRptName = corpRptName == null ? null : corpRptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.corp_rpt_name_kana
     *
     * @return the value of law_apply.corp_rpt_name_kana
     *
     * @mbg.generated
     */
    public String getCorpRptNameKana() {
        return corpRptNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.corp_rpt_name_kana
     *
     * @param corpRptNameKana the value for law_apply.corp_rpt_name_kana
     *
     * @mbg.generated
     */
    public void setCorpRptNameKana(String corpRptNameKana) {
        this.corpRptNameKana = corpRptNameKana == null ? null : corpRptNameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.corp_addr
     *
     * @return the value of law_apply.corp_addr
     *
     * @mbg.generated
     */
    public String getCorpAddr() {
        return corpAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.corp_addr
     *
     * @param corpAddr the value for law_apply.corp_addr
     *
     * @mbg.generated
     */
    public void setCorpAddr(String corpAddr) {
        this.corpAddr = corpAddr == null ? null : corpAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.corp_phone
     *
     * @return the value of law_apply.corp_phone
     *
     * @mbg.generated
     */
    public String getCorpPhone() {
        return corpPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.corp_phone
     *
     * @param corpPhone the value for law_apply.corp_phone
     *
     * @mbg.generated
     */
    public void setCorpPhone(String corpPhone) {
        this.corpPhone = corpPhone == null ? null : corpPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.applicant_name
     *
     * @return the value of law_apply.applicant_name
     *
     * @mbg.generated
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.applicant_name
     *
     * @param applicantName the value for law_apply.applicant_name
     *
     * @mbg.generated
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName == null ? null : applicantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.applicant_name_kana
     *
     * @return the value of law_apply.applicant_name_kana
     *
     * @mbg.generated
     */
    public String getApplicantNameKana() {
        return applicantNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.applicant_name_kana
     *
     * @param applicantNameKana the value for law_apply.applicant_name_kana
     *
     * @mbg.generated
     */
    public void setApplicantNameKana(String applicantNameKana) {
        this.applicantNameKana = applicantNameKana == null ? null : applicantNameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.applicant_dept
     *
     * @return the value of law_apply.applicant_dept
     *
     * @mbg.generated
     */
    public String getApplicantDept() {
        return applicantDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.applicant_dept
     *
     * @param applicantDept the value for law_apply.applicant_dept
     *
     * @mbg.generated
     */
    public void setApplicantDept(String applicantDept) {
        this.applicantDept = applicantDept == null ? null : applicantDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.applicant_phone
     *
     * @return the value of law_apply.applicant_phone
     *
     * @mbg.generated
     */
    public String getApplicantPhone() {
        return applicantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.applicant_phone
     *
     * @param applicantPhone the value for law_apply.applicant_phone
     *
     * @mbg.generated
     */
    public void setApplicantPhone(String applicantPhone) {
        this.applicantPhone = applicantPhone == null ? null : applicantPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.applicant_email
     *
     * @return the value of law_apply.applicant_email
     *
     * @mbg.generated
     */
    public String getApplicantEmail() {
        return applicantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.applicant_email
     *
     * @param applicantEmail the value for law_apply.applicant_email
     *
     * @mbg.generated
     */
    public void setApplicantEmail(String applicantEmail) {
        this.applicantEmail = applicantEmail == null ? null : applicantEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.reg_code
     *
     * @return the value of law_apply.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.reg_code
     *
     * @param regCode the value for law_apply.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.status
     *
     * @return the value of law_apply.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.status
     *
     * @param status the value for law_apply.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.reject_reason
     *
     * @return the value of law_apply.reject_reason
     *
     * @mbg.generated
     */
    public String getRejectReason() {
        return rejectReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.reject_reason
     *
     * @param rejectReason the value for law_apply.reject_reason
     *
     * @mbg.generated
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason == null ? null : rejectReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.reject_time
     *
     * @return the value of law_apply.reject_time
     *
     * @mbg.generated
     */
    public Date getRejectTime() {
        return rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.reject_time
     *
     * @param rejectTime the value for law_apply.reject_time
     *
     * @mbg.generated
     */
    public void setRejectTime(Date rejectTime) {
        this.rejectTime = rejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.remark
     *
     * @return the value of law_apply.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.remark
     *
     * @param remark the value for law_apply.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.create_time
     *
     * @return the value of law_apply.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.create_time
     *
     * @param createTime the value for law_apply.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_apply.update_time
     *
     * @return the value of law_apply.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_apply.update_time
     *
     * @param updateTime the value for law_apply.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", corpName=").append(corpName);
        sb.append(", corpRptName=").append(corpRptName);
        sb.append(", corpRptNameKana=").append(corpRptNameKana);
        sb.append(", corpAddr=").append(corpAddr);
        sb.append(", corpPhone=").append(corpPhone);
        sb.append(", applicantName=").append(applicantName);
        sb.append(", applicantNameKana=").append(applicantNameKana);
        sb.append(", applicantDept=").append(applicantDept);
        sb.append(", applicantPhone=").append(applicantPhone);
        sb.append(", applicantEmail=").append(applicantEmail);
        sb.append(", regCode=").append(regCode);
        sb.append(", status=").append(status);
        sb.append(", rejectReason=").append(rejectReason);
        sb.append(", rejectTime=").append(rejectTime);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}