package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class LawGroupCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.reg_code
     *
     * @mbg.generated
     */
    private String regCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.invalid_date
     *
     * @mbg.generated
     */
    private Date invalidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.reg_flag
     *
     * @mbg.generated
     */
    private Boolean regFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_code.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.id
     *
     * @return the value of law_group_code.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.id
     *
     * @param id the value for law_group_code.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.group_id
     *
     * @return the value of law_group_code.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.group_id
     *
     * @param groupId the value for law_group_code.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.email
     *
     * @return the value of law_group_code.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.email
     *
     * @param email the value for law_group_code.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.reg_code
     *
     * @return the value of law_group_code.reg_code
     *
     * @mbg.generated
     */
    public String getRegCode() {
        return regCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.reg_code
     *
     * @param regCode the value for law_group_code.reg_code
     *
     * @mbg.generated
     */
    public void setRegCode(String regCode) {
        this.regCode = regCode == null ? null : regCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.invalid_date
     *
     * @return the value of law_group_code.invalid_date
     *
     * @mbg.generated
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.invalid_date
     *
     * @param invalidDate the value for law_group_code.invalid_date
     *
     * @mbg.generated
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.reg_flag
     *
     * @return the value of law_group_code.reg_flag
     *
     * @mbg.generated
     */
    public Boolean getRegFlag() {
        return regFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.reg_flag
     *
     * @param regFlag the value for law_group_code.reg_flag
     *
     * @mbg.generated
     */
    public void setRegFlag(Boolean regFlag) {
        this.regFlag = regFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.created_by
     *
     * @return the value of law_group_code.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.created_by
     *
     * @param createdBy the value for law_group_code.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.create_time
     *
     * @return the value of law_group_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.create_time
     *
     * @param createTime the value for law_group_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.updated_by
     *
     * @return the value of law_group_code.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.updated_by
     *
     * @param updatedBy the value for law_group_code.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_code.update_time
     *
     * @return the value of law_group_code.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_code.update_time
     *
     * @param updateTime the value for law_group_code.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", email=").append(email);
        sb.append(", regCode=").append(regCode);
        sb.append(", invalidDate=").append(invalidDate);
        sb.append(", regFlag=").append(regFlag);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}