package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class LawGroupUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.sys_user_id
     *
     * @mbg.generated
     */
    private Long sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.login_id
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.fullname
     *
     * @mbg.generated
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.fullname_kana
     *
     * @mbg.generated
     */
    private String fullnameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.sendmail_flag
     *
     * @mbg.generated
     */
    private Boolean sendmailFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.gender
     *
     * @mbg.generated
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column law_group_user.avatar
     *
     * @mbg.generated
     */
    private byte[] avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.id
     *
     * @return the value of law_group_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.id
     *
     * @param id the value for law_group_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.group_id
     *
     * @return the value of law_group_user.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.group_id
     *
     * @param groupId the value for law_group_user.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.sys_user_id
     *
     * @return the value of law_group_user.sys_user_id
     *
     * @mbg.generated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.sys_user_id
     *
     * @param sysUserId the value for law_group_user.sys_user_id
     *
     * @mbg.generated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.login_id
     *
     * @return the value of law_group_user.login_id
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.login_id
     *
     * @param loginId the value for law_group_user.login_id
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.fullname
     *
     * @return the value of law_group_user.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.fullname
     *
     * @param fullname the value for law_group_user.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.fullname_kana
     *
     * @return the value of law_group_user.fullname_kana
     *
     * @mbg.generated
     */
    public String getFullnameKana() {
        return fullnameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.fullname_kana
     *
     * @param fullnameKana the value for law_group_user.fullname_kana
     *
     * @mbg.generated
     */
    public void setFullnameKana(String fullnameKana) {
        this.fullnameKana = fullnameKana == null ? null : fullnameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.sendmail_flag
     *
     * @return the value of law_group_user.sendmail_flag
     *
     * @mbg.generated
     */
    public Boolean getSendmailFlag() {
        return sendmailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.sendmail_flag
     *
     * @param sendmailFlag the value for law_group_user.sendmail_flag
     *
     * @mbg.generated
     */
    public void setSendmailFlag(Boolean sendmailFlag) {
        this.sendmailFlag = sendmailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.tel
     *
     * @return the value of law_group_user.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.tel
     *
     * @param tel the value for law_group_user.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.email
     *
     * @return the value of law_group_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.email
     *
     * @param email the value for law_group_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.birthday
     *
     * @return the value of law_group_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.birthday
     *
     * @param birthday the value for law_group_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.gender
     *
     * @return the value of law_group_user.gender
     *
     * @mbg.generated
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.gender
     *
     * @param gender the value for law_group_user.gender
     *
     * @mbg.generated
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.status
     *
     * @return the value of law_group_user.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.status
     *
     * @param status the value for law_group_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.created_by
     *
     * @return the value of law_group_user.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.created_by
     *
     * @param createdBy the value for law_group_user.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.create_time
     *
     * @return the value of law_group_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.create_time
     *
     * @param createTime the value for law_group_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.updated_by
     *
     * @return the value of law_group_user.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.updated_by
     *
     * @param updatedBy the value for law_group_user.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.update_time
     *
     * @return the value of law_group_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.update_time
     *
     * @param updateTime the value for law_group_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.remark
     *
     * @return the value of law_group_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.remark
     *
     * @param remark the value for law_group_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column law_group_user.avatar
     *
     * @return the value of law_group_user.avatar
     *
     * @mbg.generated
     */
    public byte[] getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column law_group_user.avatar
     *
     * @param avatar the value for law_group_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", sysUserId=").append(sysUserId);
        sb.append(", loginId=").append(loginId);
        sb.append(", fullname=").append(fullname);
        sb.append(", fullnameKana=").append(fullnameKana);
        sb.append(", sendmailFlag=").append(sendmailFlag);
        sb.append(", tel=").append(tel);
        sb.append(", email=").append(email);
        sb.append(", birthday=").append(birthday);
        sb.append(", gender=").append(gender);
        sb.append(", status=").append(status);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", avatar=").append(avatar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}