package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class OmCustomerCredit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.customer_code
     *
     * @mbg.generated
     */
    private String customerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.card_code
     *
     * @mbg.generated
     */
    private String cardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.valid_date
     *
     * @mbg.generated
     */
    private String validDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.is_selected
     *
     * @mbg.generated
     */
    private Boolean isSelected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_customer_credit.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table om_customer_credit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.id
     *
     * @return the value of om_customer_credit.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.id
     *
     * @param id the value for om_customer_credit.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.customer_id
     *
     * @return the value of om_customer_credit.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.customer_id
     *
     * @param customerId the value for om_customer_credit.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.customer_code
     *
     * @return the value of om_customer_credit.customer_code
     *
     * @mbg.generated
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.customer_code
     *
     * @param customerCode the value for om_customer_credit.customer_code
     *
     * @mbg.generated
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.card_code
     *
     * @return the value of om_customer_credit.card_code
     *
     * @mbg.generated
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.card_code
     *
     * @param cardCode the value for om_customer_credit.card_code
     *
     * @mbg.generated
     */
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode == null ? null : cardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.card_no
     *
     * @return the value of om_customer_credit.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.card_no
     *
     * @param cardNo the value for om_customer_credit.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.name
     *
     * @return the value of om_customer_credit.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.name
     *
     * @param name the value for om_customer_credit.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.company_name
     *
     * @return the value of om_customer_credit.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.company_name
     *
     * @param companyName the value for om_customer_credit.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.valid_date
     *
     * @return the value of om_customer_credit.valid_date
     *
     * @mbg.generated
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.valid_date
     *
     * @param validDate the value for om_customer_credit.valid_date
     *
     * @mbg.generated
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.is_selected
     *
     * @return the value of om_customer_credit.is_selected
     *
     * @mbg.generated
     */
    public Boolean getIsSelected() {
        return isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.is_selected
     *
     * @param isSelected the value for om_customer_credit.is_selected
     *
     * @mbg.generated
     */
    public void setIsSelected(Boolean isSelected) {
        this.isSelected = isSelected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.status
     *
     * @return the value of om_customer_credit.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.status
     *
     * @param status the value for om_customer_credit.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.created_by
     *
     * @return the value of om_customer_credit.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.created_by
     *
     * @param createdBy the value for om_customer_credit.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.create_time
     *
     * @return the value of om_customer_credit.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.create_time
     *
     * @param createTime the value for om_customer_credit.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.updated_by
     *
     * @return the value of om_customer_credit.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.updated_by
     *
     * @param updatedBy the value for om_customer_credit.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_customer_credit.update_time
     *
     * @return the value of om_customer_credit.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_customer_credit.update_time
     *
     * @param updateTime the value for om_customer_credit.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_customer_credit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerId=").append(customerId);
        sb.append(", customerCode=").append(customerCode);
        sb.append(", cardCode=").append(cardCode);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", name=").append(name);
        sb.append(", companyName=").append(companyName);
        sb.append(", validDate=").append(validDate);
        sb.append(", isSelected=").append(isSelected);
        sb.append(", status=").append(status);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}