package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class OmDeductionRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.customer_id
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.type
     *
     * @mbg.generated
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.customer_code
     *
     * @mbg.generated
     */
    private String customerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.card_code
     *
     * @mbg.generated
     */
    private String cardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.credit_holder_name
     *
     * @mbg.generated
     */
    private String creditHolderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.credit_company_name
     *
     * @mbg.generated
     */
    private String creditCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.credit_valid_date
     *
     * @mbg.generated
     */
    private String creditValidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.amount
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.deduction_date
     *
     * @mbg.generated
     */
    private Date deductionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.deduction_time
     *
     * @mbg.generated
     */
    private Date deductionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.deduction_orderno
     *
     * @mbg.generated
     */
    private String deductionOrderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.origin_deduction_orderno
     *
     * @mbg.generated
     */
    private String originDeductionOrderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.deduction_error_code
     *
     * @mbg.generated
     */
    private String deductionErrorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.metadata
     *
     * @mbg.generated
     */
    private String metadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.deduction_error_msg
     *
     * @mbg.generated
     */
    private String deductionErrorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column om_deduction_record.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table om_deduction_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.id
     *
     * @return the value of om_deduction_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.id
     *
     * @param id the value for om_deduction_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.customer_id
     *
     * @return the value of om_deduction_record.customer_id
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.customer_id
     *
     * @param customerId the value for om_deduction_record.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.type
     *
     * @return the value of om_deduction_record.type
     *
     * @mbg.generated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.type
     *
     * @param type the value for om_deduction_record.type
     *
     * @mbg.generated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.order_no
     *
     * @return the value of om_deduction_record.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.order_no
     *
     * @param orderNo the value for om_deduction_record.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.customer_code
     *
     * @return the value of om_deduction_record.customer_code
     *
     * @mbg.generated
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.customer_code
     *
     * @param customerCode the value for om_deduction_record.customer_code
     *
     * @mbg.generated
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode == null ? null : customerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.card_code
     *
     * @return the value of om_deduction_record.card_code
     *
     * @mbg.generated
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.card_code
     *
     * @param cardCode the value for om_deduction_record.card_code
     *
     * @mbg.generated
     */
    public void setCardCode(String cardCode) {
        this.cardCode = cardCode == null ? null : cardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.card_no
     *
     * @return the value of om_deduction_record.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.card_no
     *
     * @param cardNo the value for om_deduction_record.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.credit_holder_name
     *
     * @return the value of om_deduction_record.credit_holder_name
     *
     * @mbg.generated
     */
    public String getCreditHolderName() {
        return creditHolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.credit_holder_name
     *
     * @param creditHolderName the value for om_deduction_record.credit_holder_name
     *
     * @mbg.generated
     */
    public void setCreditHolderName(String creditHolderName) {
        this.creditHolderName = creditHolderName == null ? null : creditHolderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.credit_company_name
     *
     * @return the value of om_deduction_record.credit_company_name
     *
     * @mbg.generated
     */
    public String getCreditCompanyName() {
        return creditCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.credit_company_name
     *
     * @param creditCompanyName the value for om_deduction_record.credit_company_name
     *
     * @mbg.generated
     */
    public void setCreditCompanyName(String creditCompanyName) {
        this.creditCompanyName = creditCompanyName == null ? null : creditCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.credit_valid_date
     *
     * @return the value of om_deduction_record.credit_valid_date
     *
     * @mbg.generated
     */
    public String getCreditValidDate() {
        return creditValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.credit_valid_date
     *
     * @param creditValidDate the value for om_deduction_record.credit_valid_date
     *
     * @mbg.generated
     */
    public void setCreditValidDate(String creditValidDate) {
        this.creditValidDate = creditValidDate == null ? null : creditValidDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.amount
     *
     * @return the value of om_deduction_record.amount
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.amount
     *
     * @param amount the value for om_deduction_record.amount
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.desc
     *
     * @return the value of om_deduction_record.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.desc
     *
     * @param desc the value for om_deduction_record.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.deduction_date
     *
     * @return the value of om_deduction_record.deduction_date
     *
     * @mbg.generated
     */
    public Date getDeductionDate() {
        return deductionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.deduction_date
     *
     * @param deductionDate the value for om_deduction_record.deduction_date
     *
     * @mbg.generated
     */
    public void setDeductionDate(Date deductionDate) {
        this.deductionDate = deductionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.deduction_time
     *
     * @return the value of om_deduction_record.deduction_time
     *
     * @mbg.generated
     */
    public Date getDeductionTime() {
        return deductionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.deduction_time
     *
     * @param deductionTime the value for om_deduction_record.deduction_time
     *
     * @mbg.generated
     */
    public void setDeductionTime(Date deductionTime) {
        this.deductionTime = deductionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.deduction_orderno
     *
     * @return the value of om_deduction_record.deduction_orderno
     *
     * @mbg.generated
     */
    public String getDeductionOrderno() {
        return deductionOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.deduction_orderno
     *
     * @param deductionOrderno the value for om_deduction_record.deduction_orderno
     *
     * @mbg.generated
     */
    public void setDeductionOrderno(String deductionOrderno) {
        this.deductionOrderno = deductionOrderno == null ? null : deductionOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.origin_deduction_orderno
     *
     * @return the value of om_deduction_record.origin_deduction_orderno
     *
     * @mbg.generated
     */
    public String getOriginDeductionOrderno() {
        return originDeductionOrderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.origin_deduction_orderno
     *
     * @param originDeductionOrderno the value for om_deduction_record.origin_deduction_orderno
     *
     * @mbg.generated
     */
    public void setOriginDeductionOrderno(String originDeductionOrderno) {
        this.originDeductionOrderno = originDeductionOrderno == null ? null : originDeductionOrderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.deduction_error_code
     *
     * @return the value of om_deduction_record.deduction_error_code
     *
     * @mbg.generated
     */
    public String getDeductionErrorCode() {
        return deductionErrorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.deduction_error_code
     *
     * @param deductionErrorCode the value for om_deduction_record.deduction_error_code
     *
     * @mbg.generated
     */
    public void setDeductionErrorCode(String deductionErrorCode) {
        this.deductionErrorCode = deductionErrorCode == null ? null : deductionErrorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.status
     *
     * @return the value of om_deduction_record.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.status
     *
     * @param status the value for om_deduction_record.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.created_by
     *
     * @return the value of om_deduction_record.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.created_by
     *
     * @param createdBy the value for om_deduction_record.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.create_time
     *
     * @return the value of om_deduction_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.create_time
     *
     * @param createTime the value for om_deduction_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.updated_by
     *
     * @return the value of om_deduction_record.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.updated_by
     *
     * @param updatedBy the value for om_deduction_record.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.update_time
     *
     * @return the value of om_deduction_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.update_time
     *
     * @param updateTime the value for om_deduction_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.metadata
     *
     * @return the value of om_deduction_record.metadata
     *
     * @mbg.generated
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.metadata
     *
     * @param metadata the value for om_deduction_record.metadata
     *
     * @mbg.generated
     */
    public void setMetadata(String metadata) {
        this.metadata = metadata == null ? null : metadata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.deduction_error_msg
     *
     * @return the value of om_deduction_record.deduction_error_msg
     *
     * @mbg.generated
     */
    public String getDeductionErrorMsg() {
        return deductionErrorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.deduction_error_msg
     *
     * @param deductionErrorMsg the value for om_deduction_record.deduction_error_msg
     *
     * @mbg.generated
     */
    public void setDeductionErrorMsg(String deductionErrorMsg) {
        this.deductionErrorMsg = deductionErrorMsg == null ? null : deductionErrorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column om_deduction_record.remark
     *
     * @return the value of om_deduction_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column om_deduction_record.remark
     *
     * @param remark the value for om_deduction_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_deduction_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", customerId=").append(customerId);
        sb.append(", type=").append(type);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", customerCode=").append(customerCode);
        sb.append(", cardCode=").append(cardCode);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", creditHolderName=").append(creditHolderName);
        sb.append(", creditCompanyName=").append(creditCompanyName);
        sb.append(", creditValidDate=").append(creditValidDate);
        sb.append(", amount=").append(amount);
        sb.append(", desc=").append(desc);
        sb.append(", deductionDate=").append(deductionDate);
        sb.append(", deductionTime=").append(deductionTime);
        sb.append(", deductionOrderno=").append(deductionOrderno);
        sb.append(", originDeductionOrderno=").append(originDeductionOrderno);
        sb.append(", deductionErrorCode=").append(deductionErrorCode);
        sb.append(", status=").append(status);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", metadata=").append(metadata);
        sb.append(", deductionErrorMsg=").append(deductionErrorMsg);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}