package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class SysDictData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.dict_code
     *
     * @mbg.generated
     */
    private Long dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.dict_sort
     *
     * @mbg.generated
     */
    private Integer dictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.dict_label
     *
     * @mbg.generated
     */
    private String dictLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.dict_value
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.dict_type
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.css_class
     *
     * @mbg.generated
     */
    private String cssClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.list_class
     *
     * @mbg.generated
     */
    private String listClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.is_default
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_dict_data.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base..sys_dict_data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.dict_code
     *
     * @return the value of base..sys_dict_data.dict_code
     *
     * @mbg.generated
     */
    public Long getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.dict_code
     *
     * @param dictCode the value for base..sys_dict_data.dict_code
     *
     * @mbg.generated
     */
    public void setDictCode(Long dictCode) {
        this.dictCode = dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.dict_sort
     *
     * @return the value of base..sys_dict_data.dict_sort
     *
     * @mbg.generated
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.dict_sort
     *
     * @param dictSort the value for base..sys_dict_data.dict_sort
     *
     * @mbg.generated
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.dict_label
     *
     * @return the value of base..sys_dict_data.dict_label
     *
     * @mbg.generated
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.dict_label
     *
     * @param dictLabel the value for base..sys_dict_data.dict_label
     *
     * @mbg.generated
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.dict_value
     *
     * @return the value of base..sys_dict_data.dict_value
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.dict_value
     *
     * @param dictValue the value for base..sys_dict_data.dict_value
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.dict_type
     *
     * @return the value of base..sys_dict_data.dict_type
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.dict_type
     *
     * @param dictType the value for base..sys_dict_data.dict_type
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.css_class
     *
     * @return the value of base..sys_dict_data.css_class
     *
     * @mbg.generated
     */
    public String getCssClass() {
        return cssClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.css_class
     *
     * @param cssClass the value for base..sys_dict_data.css_class
     *
     * @mbg.generated
     */
    public void setCssClass(String cssClass) {
        this.cssClass = cssClass == null ? null : cssClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.list_class
     *
     * @return the value of base..sys_dict_data.list_class
     *
     * @mbg.generated
     */
    public String getListClass() {
        return listClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.list_class
     *
     * @param listClass the value for base..sys_dict_data.list_class
     *
     * @mbg.generated
     */
    public void setListClass(String listClass) {
        this.listClass = listClass == null ? null : listClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.is_default
     *
     * @return the value of base..sys_dict_data.is_default
     *
     * @mbg.generated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.is_default
     *
     * @param isDefault the value for base..sys_dict_data.is_default
     *
     * @mbg.generated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.status
     *
     * @return the value of base..sys_dict_data.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.status
     *
     * @param status the value for base..sys_dict_data.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.create_by
     *
     * @return the value of base..sys_dict_data.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.create_by
     *
     * @param createBy the value for base..sys_dict_data.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.create_time
     *
     * @return the value of base..sys_dict_data.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.create_time
     *
     * @param createTime the value for base..sys_dict_data.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.update_by
     *
     * @return the value of base..sys_dict_data.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.update_by
     *
     * @param updateBy the value for base..sys_dict_data.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.update_time
     *
     * @return the value of base..sys_dict_data.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.update_time
     *
     * @param updateTime the value for base..sys_dict_data.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_dict_data.remark
     *
     * @return the value of base..sys_dict_data.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_dict_data.remark
     *
     * @param remark the value for base..sys_dict_data.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dict_data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictCode=").append(dictCode);
        sb.append(", dictSort=").append(dictSort);
        sb.append(", dictLabel=").append(dictLabel);
        sb.append(", dictValue=").append(dictValue);
        sb.append(", dictType=").append(dictType);
        sb.append(", cssClass=").append(cssClass);
        sb.append(", listClass=").append(listClass);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}