package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class SysJob implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.job_id
     *
     * @mbg.generated
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.invoke_target
     *
     * @mbg.generated
     */
    private String invokeTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.cron_expression
     *
     * @mbg.generated
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.misfire_policy
     *
     * @mbg.generated
     */
    private String misfirePolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.concurrent
     *
     * @mbg.generated
     */
    private String concurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.update_by
     *
     * @mbg.generated
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.job_id
     *
     * @return the value of base..sys_job.job_id
     *
     * @mbg.generated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.job_id
     *
     * @param jobId the value for base..sys_job.job_id
     *
     * @mbg.generated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.job_name
     *
     * @return the value of base..sys_job.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.job_name
     *
     * @param jobName the value for base..sys_job.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.job_group
     *
     * @return the value of base..sys_job.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.job_group
     *
     * @param jobGroup the value for base..sys_job.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.invoke_target
     *
     * @return the value of base..sys_job.invoke_target
     *
     * @mbg.generated
     */
    public String getInvokeTarget() {
        return invokeTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.invoke_target
     *
     * @param invokeTarget the value for base..sys_job.invoke_target
     *
     * @mbg.generated
     */
    public void setInvokeTarget(String invokeTarget) {
        this.invokeTarget = invokeTarget == null ? null : invokeTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.cron_expression
     *
     * @return the value of base..sys_job.cron_expression
     *
     * @mbg.generated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.cron_expression
     *
     * @param cronExpression the value for base..sys_job.cron_expression
     *
     * @mbg.generated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression == null ? null : cronExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.misfire_policy
     *
     * @return the value of base..sys_job.misfire_policy
     *
     * @mbg.generated
     */
    public String getMisfirePolicy() {
        return misfirePolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.misfire_policy
     *
     * @param misfirePolicy the value for base..sys_job.misfire_policy
     *
     * @mbg.generated
     */
    public void setMisfirePolicy(String misfirePolicy) {
        this.misfirePolicy = misfirePolicy == null ? null : misfirePolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.concurrent
     *
     * @return the value of base..sys_job.concurrent
     *
     * @mbg.generated
     */
    public String getConcurrent() {
        return concurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.concurrent
     *
     * @param concurrent the value for base..sys_job.concurrent
     *
     * @mbg.generated
     */
    public void setConcurrent(String concurrent) {
        this.concurrent = concurrent == null ? null : concurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.status
     *
     * @return the value of base..sys_job.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.status
     *
     * @param status the value for base..sys_job.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.create_by
     *
     * @return the value of base..sys_job.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.create_by
     *
     * @param createBy the value for base..sys_job.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.create_time
     *
     * @return the value of base..sys_job.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.create_time
     *
     * @param createTime the value for base..sys_job.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.update_by
     *
     * @return the value of base..sys_job.update_by
     *
     * @mbg.generated
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.update_by
     *
     * @param updateBy the value for base..sys_job.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.update_time
     *
     * @return the value of base..sys_job.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.update_time
     *
     * @param updateTime the value for base..sys_job.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job.remark
     *
     * @return the value of base..sys_job.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job.remark
     *
     * @param remark the value for base..sys_job.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", invokeTarget=").append(invokeTarget);
        sb.append(", cronExpression=").append(cronExpression);
        sb.append(", misfirePolicy=").append(misfirePolicy);
        sb.append(", concurrent=").append(concurrent);
        sb.append(", status=").append(status);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}