package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class SysJobLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    private Long jobLogId;
    
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column base..sys_job_log.job_id
    *
    * @mbg.generated
    */
   private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    private String invokeTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.job_message
     *
     * @mbg.generated
     */
    private String jobMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.exception_info
     *
     * @mbg.generated
     */
    private String exceptionInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base..sys_job_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;
    
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base..sys_job_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.job_log_id
     *
     * @return the value of base..sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    public Long getJobLogId() {
        return jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.job_log_id
     *
     * @param jobLogId the value for base..sys_job_log.job_log_id
     *
     * @mbg.generated
     */
    public void setJobLogId(Long jobLogId) {
        this.jobLogId = jobLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.job_name
     *
     * @return the value of base..sys_job_log.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.job_name
     *
     * @param jobName the value for base..sys_job_log.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.job_group
     *
     * @return the value of base..sys_job_log.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.job_group
     *
     * @param jobGroup the value for base..sys_job_log.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.invoke_target
     *
     * @return the value of base..sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    public String getInvokeTarget() {
        return invokeTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.invoke_target
     *
     * @param invokeTarget the value for base..sys_job_log.invoke_target
     *
     * @mbg.generated
     */
    public void setInvokeTarget(String invokeTarget) {
        this.invokeTarget = invokeTarget == null ? null : invokeTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.job_message
     *
     * @return the value of base..sys_job_log.job_message
     *
     * @mbg.generated
     */
    public String getJobMessage() {
        return jobMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.job_message
     *
     * @param jobMessage the value for base..sys_job_log.job_message
     *
     * @mbg.generated
     */
    public void setJobMessage(String jobMessage) {
        this.jobMessage = jobMessage == null ? null : jobMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.status
     *
     * @return the value of base..sys_job_log.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.status
     *
     * @param status the value for base..sys_job_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.exception_info
     *
     * @return the value of base..sys_job_log.exception_info
     *
     * @mbg.generated
     */
    public String getExceptionInfo() {
        return exceptionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.exception_info
     *
     * @param exceptionInfo the value for base..sys_job_log.exception_info
     *
     * @mbg.generated
     */
    public void setExceptionInfo(String exceptionInfo) {
        this.exceptionInfo = exceptionInfo == null ? null : exceptionInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base..sys_job_log.create_time
     *
     * @return the value of base..sys_job_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base..sys_job_log.create_time
     *
     * @param createTime the value for base..sys_job_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    

    /**
	 * @return the jobId
	 */
	public Long getJobId() {
		return jobId;
	}

	/**
	 * @param jobId the jobId to set
	 */
	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	/**
	 * @return the endTime
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobLogId=").append(jobLogId);
        sb.append(", jobId=").append(jobId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", invokeTarget=").append(invokeTarget);
        sb.append(", jobMessage=").append(jobMessage);
        sb.append(", status=").append(status);
        sb.append(", exceptionInfo=").append(exceptionInfo);
        sb.append(", createTime=").append(createTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}