package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class UserGeneral implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.login_id
     *
     * @mbg.generated
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.famname
     *
     * @mbg.generated
     */
    private String famname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.famname_kana
     *
     * @mbg.generated
     */
    private String famnameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.givename
     *
     * @mbg.generated
     */
    private String givename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.givename_kana
     *
     * @mbg.generated
     */
    private String givenameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.fullname
     *
     * @mbg.generated
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.fullname_kana
     *
     * @mbg.generated
     */
    private String fullnameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.gender
     *
     * @mbg.generated
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.addr1
     *
     * @mbg.generated
     */
    private String addr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.addr2
     *
     * @mbg.generated
     */
    private String addr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.addr3
     *
     * @mbg.generated
     */
    private String addr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.judicial_id
     *
     * @mbg.generated
     */
    private String judicialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.law_group_id
     *
     * @mbg.generated
     */
    private String lawGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.status
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general.avatar
     *
     * @mbg.generated
     */
    private byte[] avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_general
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.user_id
     *
     * @return the value of user_general.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.user_id
     *
     * @param userId the value for user_general.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.user_name
     *
     * @return the value of user_general.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.user_name
     *
     * @param userName the value for user_general.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.login_id
     *
     * @return the value of user_general.login_id
     *
     * @mbg.generated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.login_id
     *
     * @param loginId the value for user_general.login_id
     *
     * @mbg.generated
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.password
     *
     * @return the value of user_general.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.password
     *
     * @param password the value for user_general.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.salt
     *
     * @return the value of user_general.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.salt
     *
     * @param salt the value for user_general.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.famname
     *
     * @return the value of user_general.famname
     *
     * @mbg.generated
     */
    public String getFamname() {
        return famname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.famname
     *
     * @param famname the value for user_general.famname
     *
     * @mbg.generated
     */
    public void setFamname(String famname) {
        this.famname = famname == null ? null : famname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.famname_kana
     *
     * @return the value of user_general.famname_kana
     *
     * @mbg.generated
     */
    public String getFamnameKana() {
        return famnameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.famname_kana
     *
     * @param famnameKana the value for user_general.famname_kana
     *
     * @mbg.generated
     */
    public void setFamnameKana(String famnameKana) {
        this.famnameKana = famnameKana == null ? null : famnameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.givename
     *
     * @return the value of user_general.givename
     *
     * @mbg.generated
     */
    public String getGivename() {
        return givename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.givename
     *
     * @param givename the value for user_general.givename
     *
     * @mbg.generated
     */
    public void setGivename(String givename) {
        this.givename = givename == null ? null : givename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.givename_kana
     *
     * @return the value of user_general.givename_kana
     *
     * @mbg.generated
     */
    public String getGivenameKana() {
        return givenameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.givename_kana
     *
     * @param givenameKana the value for user_general.givename_kana
     *
     * @mbg.generated
     */
    public void setGivenameKana(String givenameKana) {
        this.givenameKana = givenameKana == null ? null : givenameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.fullname
     *
     * @return the value of user_general.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.fullname
     *
     * @param fullname the value for user_general.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.fullname_kana
     *
     * @return the value of user_general.fullname_kana
     *
     * @mbg.generated
     */
    public String getFullnameKana() {
        return fullnameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.fullname_kana
     *
     * @param fullnameKana the value for user_general.fullname_kana
     *
     * @mbg.generated
     */
    public void setFullnameKana(String fullnameKana) {
        this.fullnameKana = fullnameKana == null ? null : fullnameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.gender
     *
     * @return the value of user_general.gender
     *
     * @mbg.generated
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.gender
     *
     * @param gender the value for user_general.gender
     *
     * @mbg.generated
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.birthday
     *
     * @return the value of user_general.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.birthday
     *
     * @param birthday the value for user_general.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.email
     *
     * @return the value of user_general.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.email
     *
     * @param email the value for user_general.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.tel
     *
     * @return the value of user_general.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.tel
     *
     * @param tel the value for user_general.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.postcode
     *
     * @return the value of user_general.postcode
     *
     * @mbg.generated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.postcode
     *
     * @param postcode the value for user_general.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.addr1
     *
     * @return the value of user_general.addr1
     *
     * @mbg.generated
     */
    public String getAddr1() {
        return addr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.addr1
     *
     * @param addr1 the value for user_general.addr1
     *
     * @mbg.generated
     */
    public void setAddr1(String addr1) {
        this.addr1 = addr1 == null ? null : addr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.addr2
     *
     * @return the value of user_general.addr2
     *
     * @mbg.generated
     */
    public String getAddr2() {
        return addr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.addr2
     *
     * @param addr2 the value for user_general.addr2
     *
     * @mbg.generated
     */
    public void setAddr2(String addr2) {
        this.addr2 = addr2 == null ? null : addr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.addr3
     *
     * @return the value of user_general.addr3
     *
     * @mbg.generated
     */
    public String getAddr3() {
        return addr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.addr3
     *
     * @param addr3 the value for user_general.addr3
     *
     * @mbg.generated
     */
    public void setAddr3(String addr3) {
        this.addr3 = addr3 == null ? null : addr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.judicial_id
     *
     * @return the value of user_general.judicial_id
     *
     * @mbg.generated
     */
    public String getJudicialId() {
        return judicialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.judicial_id
     *
     * @param judicialId the value for user_general.judicial_id
     *
     * @mbg.generated
     */
    public void setJudicialId(String judicialId) {
        this.judicialId = judicialId == null ? null : judicialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.law_group_id
     *
     * @return the value of user_general.law_group_id
     *
     * @mbg.generated
     */
    public String getLawGroupId() {
        return lawGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.law_group_id
     *
     * @param lawGroupId the value for user_general.law_group_id
     *
     * @mbg.generated
     */
    public void setLawGroupId(String lawGroupId) {
        this.lawGroupId = lawGroupId == null ? null : lawGroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.status
     *
     * @return the value of user_general.status
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.status
     *
     * @param status the value for user_general.status
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.create_time
     *
     * @return the value of user_general.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.create_time
     *
     * @param createTime the value for user_general.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.update_time
     *
     * @return the value of user_general.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.update_time
     *
     * @param updateTime the value for user_general.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general.avatar
     *
     * @return the value of user_general.avatar
     *
     * @mbg.generated
     */
    public byte[] getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general.avatar
     *
     * @param avatar the value for user_general.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", loginId=").append(loginId);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", famname=").append(famname);
        sb.append(", famnameKana=").append(famnameKana);
        sb.append(", givename=").append(givename);
        sb.append(", givenameKana=").append(givenameKana);
        sb.append(", fullname=").append(fullname);
        sb.append(", fullnameKana=").append(fullnameKana);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", email=").append(email);
        sb.append(", tel=").append(tel);
        sb.append(", postcode=").append(postcode);
        sb.append(", addr1=").append(addr1);
        sb.append(", addr2=").append(addr2);
        sb.append(", addr3=").append(addr3);
        sb.append(", judicialId=").append(judicialId);
        sb.append(", lawGroupId=").append(lawGroupId);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", avatar=").append(avatar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}