package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class UserTelValidateCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.invalid_time
     *
     * @mbg.generated
     */
    private Date invalidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.link_id
     *
     * @mbg.generated
     */
    private String linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.send_status
     *
     * @mbg.generated
     */
    private String sendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.send_result
     *
     * @mbg.generated
     */
    private String sendResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tel_validate_code.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_tel_validate_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.id
     *
     * @return the value of user_tel_validate_code.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.id
     *
     * @param id the value for user_tel_validate_code.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.tel
     *
     * @return the value of user_tel_validate_code.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.tel
     *
     * @param tel the value for user_tel_validate_code.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.code
     *
     * @return the value of user_tel_validate_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.code
     *
     * @param code the value for user_tel_validate_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.invalid_time
     *
     * @return the value of user_tel_validate_code.invalid_time
     *
     * @mbg.generated
     */
    public Date getInvalidTime() {
        return invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.invalid_time
     *
     * @param invalidTime the value for user_tel_validate_code.invalid_time
     *
     * @mbg.generated
     */
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.link_id
     *
     * @return the value of user_tel_validate_code.link_id
     *
     * @mbg.generated
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.link_id
     *
     * @param linkId the value for user_tel_validate_code.link_id
     *
     * @mbg.generated
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId == null ? null : linkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.send_status
     *
     * @return the value of user_tel_validate_code.send_status
     *
     * @mbg.generated
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.send_status
     *
     * @param sendStatus the value for user_tel_validate_code.send_status
     *
     * @mbg.generated
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus == null ? null : sendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.send_result
     *
     * @return the value of user_tel_validate_code.send_result
     *
     * @mbg.generated
     */
    public String getSendResult() {
        return sendResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.send_result
     *
     * @param sendResult the value for user_tel_validate_code.send_result
     *
     * @mbg.generated
     */
    public void setSendResult(String sendResult) {
        this.sendResult = sendResult == null ? null : sendResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.create_time
     *
     * @return the value of user_tel_validate_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.create_time
     *
     * @param createTime the value for user_tel_validate_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tel_validate_code.update_time
     *
     * @return the value of user_tel_validate_code.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tel_validate_code.update_time
     *
     * @param updateTime the value for user_tel_validate_code.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tel_validate_code
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tel=").append(tel);
        sb.append(", code=").append(code);
        sb.append(", invalidTime=").append(invalidTime);
        sb.append(", linkId=").append(linkId);
        sb.append(", sendStatus=").append(sendStatus);
        sb.append(", sendResult=").append(sendResult);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}