package cn.repeatlink.common.entity;

import java.io.Serializable;
import java.util.Date;

public class UserGeneralAttribute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.marriage
     *
     * @mbg.generated
     */
    private Short marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.children
     *
     * @mbg.generated
     */
    private Integer children;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_general_attribute.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_general_attribute
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.user_id
     *
     * @return the value of user_general_attribute.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.user_id
     *
     * @param userId the value for user_general_attribute.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.position
     *
     * @return the value of user_general_attribute.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.position
     *
     * @param position the value for user_general_attribute.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.marriage
     *
     * @return the value of user_general_attribute.marriage
     *
     * @mbg.generated
     */
    public Short getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.marriage
     *
     * @param marriage the value for user_general_attribute.marriage
     *
     * @mbg.generated
     */
    public void setMarriage(Short marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.children
     *
     * @return the value of user_general_attribute.children
     *
     * @mbg.generated
     */
    public Integer getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.children
     *
     * @param children the value for user_general_attribute.children
     *
     * @mbg.generated
     */
    public void setChildren(Integer children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.phone_number
     *
     * @return the value of user_general_attribute.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.phone_number
     *
     * @param phoneNumber the value for user_general_attribute.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_general_attribute.update_time
     *
     * @return the value of user_general_attribute.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_general_attribute.update_time
     *
     * @param updateTime the value for user_general_attribute.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_attribute
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", position=").append(position);
        sb.append(", marriage=").append(marriage);
        sb.append(", children=").append(children);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}