spring:
  datasource:
    url: jdbc:mysql://localhost:3307/legalcloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    #driverClassName: com.mysql.jdbc.Driver 
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 100
    initialSize: 10
    maxWait: 600
    type: com.alibaba.druid.pool.DruidDataSource

    
  i18n:
    basename: message/frameworkmessage,message/managemessage,message/usercentermessage,message/judicialmessage
  swagger:
    enable: true
    
# json序列化设置a
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
   
  cache:
    ehcache:
      config: classpath:cache/ehcache.xml
      
mybatis:
  mapper-locations: classpath:mappers*/**/*.xml
  executor-type: reuse
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#pagehelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
  page-size-zero: false

rlframework:
  download:
    base-path: /demo/downloads

server:
  servlet:
    context-path: /legalcloud
  port: 8080
