package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.CaseBuyer;
import java.util.List;

public interface CaseBuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    int insert(CaseBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    CaseBuyer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    List<CaseBuyer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_buyer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseBuyer record);
}