package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.CaseEstateRecordUser;
import java.util.List;

public interface CaseEstateRecordUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    int insert(CaseEstateRecordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    CaseEstateRecordUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    List<CaseEstateRecordUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_estate_record_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaseEstateRecordUser record);
}