package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.EstateProtectionOrder;
import java.util.List;

public interface EstateProtectionOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    int insert(EstateProtectionOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    EstateProtectionOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    List<EstateProtectionOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estate_protection_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EstateProtectionOrder record);
}