package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.LawApply;
import java.util.List;

public interface LawApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    int insert(LawApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    LawApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    List<LawApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawApply record);
}