package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.LawGroupUser;
import java.util.List;

public interface LawGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    int insert(LawGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    LawGroupUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    List<LawGroupUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawGroupUser record);
}