package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.LawGroupCode;
import java.util.List;

public interface LawGroupCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    int insert(LawGroupCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    LawGroupCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    List<LawGroupCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawGroupCode record);
}