package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.LawGroup;
import java.util.List;

public interface LawGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group
     *
     * @mbg.generated
     */
    int insert(LawGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group
     *
     * @mbg.generated
     */
    LawGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group
     *
     * @mbg.generated
     */
    List<LawGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table law_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LawGroup record);
}