package cn.repeatlink.common.mapper;

import java.util.List;

import cn.repeatlink.common.entity.SysDept;
import cn.repeatlink.module.manage.dto.DeptInfo;

public interface SysDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dept
     *
     * @mbg.generated
     */
    int insert(SysDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dept
     *
     * @mbg.generated
     */
    SysDept selectByPrimaryKey(Long deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dept
     *
     * @mbg.generated
     */
    List<SysDept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDept record);
    
    List<DeptInfo> search(DeptInfo deptInfo);
}