package cn.repeatlink.common.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.repeatlink.common.entity.SysJob;
import cn.repeatlink.module.manage.dto.JobInfo;

public interface SysJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("jobId") Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    int insert(SysJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    SysJob selectByPrimaryKey(@Param("jobId") Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    List<SysJob> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysJob record);
    
    SysJob selectByJobId(@Param("jobId") Long jobId);
    
    List<JobInfo> search(JobInfo jobInfo);
}