package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.SysMenu;
import java.util.List;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_menu
     *
     * @mbg.generated
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_menu
     *
     * @mbg.generated
     */
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_menu
     *
     * @mbg.generated
     */
    List<SysMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMenu record);
    
    List<SysMenu> selectAllBySort();
    
    List<SysMenu> selectAllByRole(Long roleId);
}