package cn.repeatlink.common.mapper;

import java.util.List;

import cn.repeatlink.common.entity.SysOperLog;
import cn.repeatlink.module.manage.dto.OperLogInfo;

public interface SysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int insert(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    SysOperLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    List<SysOperLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_oper_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysOperLog record);
    
    List<OperLogInfo> search(OperLogInfo operLogInfo);
}