package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.SysRoleMenu;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") Long roleId, @Param("menuId") Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role_menu
     *
     * @mbg.generated
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role_menu
     *
     * @mbg.generated
     */
    SysRoleMenu selectByPrimaryKey(@Param("roleId") Long roleId, @Param("menuId") Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role_menu
     *
     * @mbg.generated
     */
    List<SysRoleMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleMenu record);
    
    List<SysRoleMenu> selectAllByRole(Long roleId);
    
    List<SysRoleMenu> selectAllByRole4Menu(Long roleId);
}