package cn.repeatlink.common.mapper;

import java.util.List;

import cn.repeatlink.common.entity.SysRole;
import cn.repeatlink.module.manage.dto.RoleInfo;
import cn.repeatlink.module.manage.dto.RoleSimpleInfo;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role
     *
     * @mbg.generated
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role
     *
     * @mbg.generated
     */
    SysRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role
     *
     * @mbg.generated
     */
    List<SysRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base..sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRole record);
    
    List<RoleInfo> search(RoleInfo	 roleInfo);
    
    List<RoleSimpleInfo> selectAllSimpleList();
}