package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.UserGeneralFace;
import java.util.List;

public interface UserGeneralFaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_face
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_face
     *
     * @mbg.generated
     */
    int insert(UserGeneralFace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_face
     *
     * @mbg.generated
     */
    UserGeneralFace selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_face
     *
     * @mbg.generated
     */
    List<UserGeneralFace> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general_face
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGeneralFace record);
}