package cn.repeatlink.common.mapper;

import cn.repeatlink.common.entity.UserGeneral;
import java.util.List;

public interface UserGeneralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    int insert(UserGeneral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    UserGeneral selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    List<UserGeneral> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_general
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGeneral record);
}